[package]
name = "actix-sse"
version = "0.1.0"
authors = ["minhld <minhledinh@admicro.vn>"]

[dependencies]
#rand = "*"
bytes = "0.4"
byteorder = "1.1"
futures = "0.1.21"
tokio = "0.1.7"
env_logger = "*"

#serde = "1.0"
#serde_json = "1.0"

actix = "0.7"
actix-web = "0.7"